pluginpal/strapi-plugin-publisher

- README.md
- admin/src/components/Action/ActionFooter/index.js
- refactor(ActionFooter): add button icons
- refactor(ActionFooter): indicate publish as the primary action
- chore(README): add note for clean rebuild
> refactor: improve button ux

- package.json
- server/services/emit-service.js
- server/services/index.js
- server/services/publication-service.js
> fix: trigger webhook on publication state toggle

- admin/src/translations/fr.json
- server/config/cron-tasks.js
> fix (cronTasks): account for new date filter format , feat(translations): add french

- package.json
> fix(peer deps):  versions should match strapis

- package.json
> Make plugin compatible with node v18.x.x

- README.md
- package.json
- server/config/cron-tasks.js
- server/config/index.js
- server/config/schema.js
- server/controllers/action-controller.js
- server/index.js
- server/services/index.js
- server/services/publication-service.js
- server/services/settings-service.js
- server/utils/getPluginService.js
> feat(cron): make action check frequency configurable

- README.md
- admin/src/api/settings.js
- admin/src/components/Action/ActionContent/index.js
- admin/src/components/Action/index.js
- server/config/index.js
- server/controllers/index.js
- server/controllers/settings-controller.js
- server/routes/index.js
- server/routes/settings-routes.js
> feat(DateTimePicker): make steps configurable

- README.md
This PR fixes the readme that had an incorrect configuration for actions
> fix(readme): incorrect actions config

- README.md
> docs(README): add instructions for clean admin rebuild

- server/config/cron-tasks.js
This converts to the object format of tasks so redcron can support it https://github.com/excl-networks/strapi-plugin-redcron
> refactor(cron): use object format

- server/services/publication-service.js
- server/utils/populate.js
> fix(webhook): add missing relations on webhook events

- server/utils/populate.js
- server/utils/relations.js
> fix(webhook): localize used functions from strapi utils

- .eslintrc.backend.js
- package.json
- yarn.lock
Removes direct listing of peerdeps aside fom the required s`@strapi/strapi` for plugins. Should resolve any peerdep issues.
Should Resolve
#70 
#71
> fix(deps): prevent peerdep errors

- server/config/index.js
- server/services/publication-service.js
Ensure toggled entity exists before attempting publication status mutation.
Resolves #69
> fix(toggle): only toggle current existing entities

- package.json
> chore(release): 1.3.5

- package.json
- yarn.lock
- fix(deps): ensure non host deps are direct deps
- chore(deps): update to latest
Resolves #77
> fix(deps): ensure non host deps are direct deps

- admin/src/components/Action/ActionFooter/index.js
- admin/src/components/Action/index.js
- fix(actions): roles without permissions to publish should not be able to set dates
> fix(actions): respect role permissions

- admin/src/components/Action/ActionContent/ActionContent.css
- admin/src/components/Action/ActionContent/index.js
> fix(action date time picker): wrap row for smaller screens

- admin/src/components/Action/Action.js
- admin/src/translations/en.json
This PR fixes a bug where required fields where not validated to be present before allowing a publish date to be set.
resolves #89
> fix(publish): ensure required fields are set before saving publish date

- package.json
> chore(release): 1.4.0

- admin/src/components/Action/Action.js
- admin/src/components/Action/ActionDateTimePicker/ActionDateTimePicker.js
- admin/src/components/ActionManager/ActionManager.js
This PR replaces the deprecated `size` attribute with the supported equivalent `spacing`.
> refactor(Stack): remove deprecated attribute

- package.json
> chore(release): 1.4.1

- admin/src/components/Action/Action.js
little PR adding the missing mode attribute
> fix: add mode attribute to actionDatePicker

- package.json
This release introduces the following changes
- #109 
- #110 
- #111
> chre(release): 1.5.0

- package.json
- yarn.lock
This PR updates the package meta to latest engine and dependancy versions.
It also adds a new release with the following changes
- #116 
- #117
> chore: package updates

- package.json
- yarn.lock
This PR adds a release with the following changes
- #125
> chore(release): 1.5.3

- package.json
This PR creates a new release with the following changes
- #122
> chore(release): 1.5.4

- package.json
This PR adds a new release with the following changes:
- #136
> chore(release): 1.5.7

- admin/src/components/ActionManager/ActionManager.tsx
- package.json
- yarn.lock
-Update react-router-dom dependency 
- Fix build error when using npm
- run: `npm run start`
> feat: update react-router-dom in package.json

- server/services/publication-service.js
- Fix some edge cases with publishing or unpublishing
- Fix some edge cases with publishing or unpublishing
- Publish modified document
> feat: rewrite logic for published or draft entities

- server/services/settings-service.js
> fix: resolve issue with model config namespace notation

- package.json
> Allow node 22

- admin/src/components/ActionManager/ActionManager.tsx
Addresses https://github.com/pluginpal/strapi-plugin-publisher/issues/202
What does it do?
-Fix flickering publisher panel
-Clean-up code for better readability 
Why is it needed?
-Fix flickering publisher panel
How to test?
Set plugin.ts config to:
'publisher': {
enabled: true,
config: {
contentTypes: ['api::article.article'],
},
},
Refresh article and page as example and see if there is no react error popping up or any other weird behaviour
> refactor: ActionManagerComponent.tsx and fix rare render race condition

- server/services/publication-service.js
> fix: use locale when checking published and draft entities in publication service
